### ISSUE TITLE
Get this error while running package

### ISSUE THREAD

**Issue by testwts** [navneetrai/laravel-subscription#1]
FatalErrorException in TwoCheckout.php line 10: Declaration of Userdesk\Subscription\Services\TwoCheckout::complete() must be compatible with Userdesk\Subscription\Contracts\Service::complete(Userdesk\Subscription\Contracts\int $id, Userdesk\Subscription\Contracts\Product $product, Userdesk\Subscription\Contracts\Consumer $consumer)

**Comment by navneetrai** [comment]
Can you please try again. I have pushed some updates. 

I tried and it is working correctly at my end. It should be working fine now.
