### ISSUE TITLE
Compatibility errors with TwoCheckout while using paypal

### ISSUE THREAD

**Issue by omerfarooX** [navneetrai/laravel-subscription#2]
Hello navneetrai,
I really like the simple approach of this library and was trying to implement the paypal express checkout gateway for subscriptions but i am facing some errors. And here are my questions

1) In the docs it says that processor is to be called statically, but it is not a static function.
`$paypal = Subscription::processor('Paypal');`

2) After calling the subscription class normally, i get another error
`Declaration of Userdesk\Subscription\Services\TwoCheckout::complete() must be compatible with Userdesk\Subscription\Contracts\Service::complete(Userdesk\Subscription\Contracts\int $id, Userdesk\Subscription\Contracts\Product $product, Userdesk\Subscription\Contracts\Consumer $consumer)`

3) How do you send you redirect the user to paypal. Can you please show some codes?

**For your reference here is my code**
`$subscription = new Subscription();
        $processor = $subscription->processor('Paypal');

```
    $userData = array(
        'name' => 'Omer Farooq',
        'address' => 'Times Square',
        'city' => 'New York',
        'state' => 'KPK',
        'zip' => 20213,
        'country' => 'United States',
        'email' => 'test@gmail.com',
        'phone' => '+11231231232'
    );
    $consumer = new SubscriptionConsumer($userData['name'], $userData['address'], $userData['city'], $userData['state'], $userData['zip'], $userData['country'], $userData['email'], $userData['phone'] );

    $productData = array(
        'title' => 'Subscription Plan 1',
        'price' => 49.9,
        'description' => 'Subscription Plan 1',
        'ipnUrl' => 'http://example.com/ipn',
        'returnUrl' => 'http://example.com/subscriptions',
        'cancelUrl' => 'http://example.com/subscriptions',
        'frequency' => 1,
        'recurrence' => 'month',
        'discount' => 0
    );
    $product = new SubscriptionProduct($productData['title'], $productData['price'], $productData['description'], $productData['ipnUrl'], $productData['returnUrl'], $productData['cancelUrl'], $productData['discount'], $productData['frequency'], $productData['recurrence'], $productData['discount'] );

    $id = Str::random(30);
    $processor->complete($id, $product, $consumer);`
```

**Comment by navneetrai** [comment]
Hi Omer,

Thanks for your interest in this :)

1) Subscription::processor is working through [laravel facades](https://laravel.com/docs/5.2/facades), so no static function is needed. It is basically creating an instance of the required service with right configuration. It is also helpful in creating aliases (i.e. 2checkout for TwoCheckout, etc.)

If you are not using laravel 5.2+ or if you do not want to add Subscription Facade to your laravel project, you'll need to call to instentiate the service manually and pass the required config to it.

2)  Can you please make sure you are at version 1.0.3. From what I can see, method signature for complete should not be blank in 1.0.3

3) Redirection is handled by complete method in each service. All I am doing is creating a list of params and building the redirection url from it.

`$redir_url = sprintf('https://www.paypal.com/cgi-bin/webscr?%s', http_build_query($params));
return redirect()->away($redir_url);`

Best Regards,
Navneet Rai

**Comment by omerfarooX** [comment]
Hello Navneet,
Sorry i never mentioned about the version of laravel i am using. I am on
5.2 and i am using the latest version of laravel-subscription package. I
have tried using using the facade as well but there is still some kind of
error with 2checkout, anyways i guess i am doing something wrong. It would
be really really great if you could just share a small portion of the code
where you create the consumer and the product and then complete the order
and then redirect to the paypal site. You can also share this code in the
readme file which would be really awesome.

Thanks for your help and great package :)
Omer Farooq

**Comment by navneetrai** [comment]
Hi Omer,

The code I am using on a production website is quite similar to what I have given as example and what you have sent to me earlier.

I mainly stripped all the references for my internal classes used for storing carts, products and user data in DB.

The code at my end is looking like this.
`
#################Internal Code for creating/fetching a cart###################
if(!empty($request->cookie('cart_id'))){
    $cart = Auth::user()->carts->find($request->cookie('cart_id'));
}

if(empty($cart) || !empty($cart->ident)){
    $cart = Cart::create([]);
    Auth::user()->carts()->save($cart);
}

$cart->update(['ip'=>$request->ip(), 'active'=>false, 'processor'=>$proc, 'amount_expected'=>$package->discounted_first_price]);
$cart->package()->associate($package);
if(!empty($coupon)){
    $cart->coupon()->associate($coupon);
}

$cart->save();

#################Payment Processing code###################
$processor = Subscription::processor($proc);
$product = new SubscriptionProduct($cart->package->title, $cart->package->discounted_price, $cart->package->description, route('billing.ipn', ['proc'=>$proc]), route('billing.cartComplete', ['proc'=>$proc), route('billing.cartReturn', ['proc'=>$proc]), $cart->package->frequency, $cart->package->recurrence, $cart->package->discounted_rebate);

if($proc == 'paypal'){
    return $processor->complete($cart->id, $product);
}else{
    $consumer = new SubscriptionConsumer($cart->user->name, $cart->user->profile->address, $cart->user->profile->city, $cart->user->profile->state, $cart->user->profile->zip, $cart->user->profile->country, $cart->user->email, $cart->user->profile->phone);

```
return $processor->complete($cart->id, $product, $consumer);
```

}
`

Hope this helps. At my end, I am able to reach the payment page for all three payment processor right now.

If you can send any log file or screenshots I might be able to help you resolve the issue.

Best Regards,
Navneet Rai

**Comment by omerfarooX** [comment]
Hello navneetrai,
Sorry for the long delay in getting back to this. Really appreciate on sharing your code, but unfortunately i still i have the same errors popping up (tried it both ways, as a facade and as a normal class). 

Just to remove any further confusion i have started from a fresh laravel installation and configured your package, and have invited you to the repo. I am not using any cart so its literally the same code i showed in the beginning. I am working on a local environment, so apart from ipn hopefully it should not effect anything else. I would be glad if you could point out any issues.

**Comment by omerfarooX** [comment]
Sorry i forgot to mention the repository, you could find it [here](https://github.com/omer414/laravel-paypal-integration). I have already invited you to the repository. Let me know if there is anything else i could do from my end.

**Comment by omerfarooX** [comment]
Hello navneetrai, 
Sorry for bothering you again, i totally understand that you might be very busy. Just wondering if you ever got time to check this out. I have invited you to my dummy repository, It is a sample repository and only includes your package, to understand how its working.

**It only has 1 controller with 1 method, which i expect should direct me to paypal's website. [Link to Controller](https://github.com/omer414/laravel-paypal-integration/blob/master/app/Http/Controllers/PaypalController.php)**

Really appreciate your help on this :)

**Comment by navneetrai** [comment]
Hi Omer,

I did visited your project, but I found a lot of files unrelated to project and a dummy readme, so I thought you might still be prepping the repo.

From what I can see, the controller code looks fine. I have never used a facade this way though. If I am not using a facade through laravel, I try to create service directly in code. 

I was just a little busy with one of my websites. I'll surely check out your project some more as soon as I will get some free time.

BTW, this website is also adding laravel-subscription, so I am expecting a much more thorough test in next few days.

**Comment by omerfarooX** [comment]
Thankyou navneetrai, 
Yes this is just a demo repository for the sake of testing this library. I am totally fine with having a laravel facade, like you are saying. But i am just too confused to create it. I have been trying to use payum as well but it lacks too much documentation, so your library is my obvious priority. 

No hurries, but when you get some time i would appreciate if you could make necessary changes to my repository. All i want to see is a controller that will eventually redirect to the paypal page to create the subscription. Working with ipn shouldn't be too much of an issue as it has lots of libraries and info already available.

Thanks again for all your hardwork and support :)

**Comment by navneetrai** [comment]
Hi @omer414 ,

I have pushed some more updates to repo. I am now fully using this code in a live website with both IPN and PDT fully working for Paypal and CCNow.
