### ISSUE TITLE
How to run tests?

### ISSUE THREAD

**Issue by nikolasp** [navneetrai/laravel-subscription#3]
Hi @navneetrai ,

How do you run tests for this package? I ask because when I run tests laravel Config class is unavailable for cloned project. Do I need run this from existing Laravel app?

Thanks

**Comment by navneetrai** [comment]
Hi @nikolasp 

I am running these test through TravisCI and PHPUnit.

I am also running my test in a deployed laravel project with config file.

**Comment by nikolasp** [comment]
Thanks for answer @navneetrai
